include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    prefer_final_fields: false
    use_key_in_widget_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
    avoid_print: false

# This file determines how strict Flutter should be when analyzing your code. Since this is your first foray into Flutter,
# you're telling the analyzer to take it easy. You can always tune this later. In fact, as you get closer to publishing
# an actual production app, you will almost certainly want to make the analyzer stricter than this.